tests/serial_test: Enable serial tests for arm*-efi and loongarch64-efi
The `serial_test` script previously skipped `arm*-efi` and
`loongarch64-efi` targets because it assumed an x86-specific PCI
serial card (`-device pci-serial`). ARM and LoongArch use
memory-mapped UARTs instead.

This patch updates the test for these architectures to target the
firmware-provided `efi0` port.

verified for aarch64-efi (arm64-efi)

Signed-off-by: Josue Hernandez <josherna@redhat.com>
Reviewed-by: Avnish Chouhan <avnish@linux.ibm.com>
Reviewed-by: Rocker Zhang <zhang.rocker.liyuan@gmail.com>
Reviewed-by: Sudhakar Kuppusamy <sudhakar@linux.ibm.com>
Part-of: <https://gitlab.freedesktop.org/gnu-grub/grub/-/merge_requests/150>

diff --git a/tests/serial_test.in b/tests/serial_test.in
--- a/tests/serial_test.in
+++ b/tests/serial_test.in
@@ -32,27 +32,31 @@ case "${grub_modinfo_target_cpu}-${grub_modinfo_platform}" in
     # FIXME: How do we setup serial ports in QEMU for these platforms?
     *-ieee1275)
 	exit 77;;
-    # FIXME: grub_pciserial_init() is built only for i386/x86_64 (see
-    # grub-core/term/serial.c), so the serial_pci probe below cannot work
-    # on these platforms.
-    arm*-efi | loongarch64-efi)
-	exit 77;;
 esac
 
-# Figure out the PCI device ID that the serial device will be on.
-output=$(echo terminal_output | "${grubshell}" --qemu-opts="-device pci-serial")
-PCIID=$(echo "$output" | grep -o "serial_pci,..:..\.." | cut -d, -f2)
+case "${grub_modinfo_target_cpu}-${grub_modinfo_platform}" in
+    arm*-efi | loongarch64-efi)
+	SERIAL_PORT="efi0"
+	set --
+	;;
+    *)
+	# Figure out the PCI device ID that the serial device will be on.
+	output=$(echo terminal_output | "${grubshell}" --qemu-opts="-device pci-serial")
+	PCIID=$(echo "$output" | grep -o "serial_pci,..:..\.." | cut -d, -f2)
 
-if [ -z "$PCIID" ]; then
-  echo "Failed to find QEMU serial device." >&2
-  echo "${output}" >&2
-  exit 99
-fi
+	if [ -z "$PCIID" ]; then
+	  echo "Failed to find QEMU serial device." >&2
+	  echo "${output}" >&2
+	  exit 99
+	fi
+	SERIAL_PORT="pci,${PCIID}"
+        # Set positional parameter $1 to the safely encapsulated string
+        set -- --qemu-opts="-chardev file,path=/dev/stdout,id=ser1 -device pci-serial,chardev=ser1"
+	;;
+esac
 
 # Test serial output via an emulated PCI serial card.
-output=$(echo "terminal_output; hello" | \
-  "${grubshell}" --serial="pci,${PCIID}" \
-    --qemu-opts="-chardev file,path=/dev/stdout,id=ser1 -device pci-serial,chardev=ser1")
+output=$(echo "terminal_output; hello" | "${grubshell}" --serial="${SERIAL_PORT}" "$@")
 
 v=$(echo -e "$output" | tail -n1)
 if [ "$v" != "Hello World" ]; then
