* Migrate kopt from menu.lst.  (Closes: #461164, #464918)

diff --git a/debian/grub-pc.postinst b/debian/grub-pc.postinst
--- a/debian/grub-pc.postinst
+++ b/debian/grub-pc.postinst
@@ -11,6 +11,16 @@ case "$1" in
       grub-mkdevicemap --no-floppy
     fi
 
+    db_get grub-pc/linux_cmdline
+    if [ "$RET" == "fillme" ] ; then
+      # wtf?!
+      echo "Internal error in grub-pc package.  Please file a bug report." >&2
+      exit 1
+    elif [ "$RET" != "" ] ; then
+      sed -i /etc/default/grub -e "s/^\(GRUB_CMDLINE_LINUX\)=.*/\1=\"$RET\"/g"
+      db_set grub-pc/linux_cmdline "" || true
+    fi
+
     db_get grub-pc/chainload_from_menu.lst
     if $RET && test -e /boot/grub/menu.lst && ! test -e /boot/grub/core.img ; then
       # If there's no core.img setup, create one (but do not risk writing to MBR).
